### ISSUE TITLE
Red log entries when infused is used with ChangeDresser

### ISSUE THREAD

**Issue by Pichu0102** [notfood/RimWorld-Infused#1]
If you use both Infused and ChangeDresser, when a pawn goes to drop off a new piece of apparel into the dresser that will have an infusion, it throws an error to the log as the pawn stops for a moment. Only does this when the apparel will give the infused notice, however, if the apparel won't be infused when they drop it in, there's no red error, nor small pause on pawns.

https://git.io/fpXlL

Minor issue, only causes log to fill and pawns to pause for a few seconds before they resume.

**Comment by notfood** [comment]
Thanks for reporting. Can you test master?

Attempted fix by https://github.com/notfood/RimWorld-Infused/commit/bca21c76af071c9959535c4fc81c4fd08c575afd

**Comment by Pichu0102** [comment]
No change in behavior.

https://git.io/fpX2D

**Comment by notfood** [comment]
Another try by https://github.com/notfood/RimWorld-Infused/commit/57c0aaf3c47978c890c85937c04bff7be564e481

Test it please.

**Comment by Pichu0102** [comment]
Didn't take. https://git.io/fpMc0

It might have something to do with the "Your item X, is infused!" message as it will duplicate this message when the dresser is emptied, leading to a lot of "Your item is infused" duplicate messages when, as an example, talking to a trader. It will only duplicate the message once, though. It seems to occur mainly if the apparel hasn't yet touched the ground at least once before being put in a storage container.

**Comment by notfood** [comment]
Try 3. https://github.com/notfood/RimWorld-Infused/commit/3de0e1b4c998bf3fc2d3fed83e62a6cfea4268ba

This one will fix it for real, I believe.

**Comment by Pichu0102** [comment]
And that's fixed it!
