### ISSUE TITLE
Unable to translate Allowance

### ISSUE THREAD

**Issue by C-ljur** [notfood/RimWorld-Infused#12]
I am unable to translate some sections about allowance for infusions, am I just missing something? Is there a way to do this?

![スクリーンショット 2022-06-14 195745](https://user-images.githubusercontent.com/97950128/173562835-fcd212fc-8c04-4183-8ba6-b60f1b999beb.png)
![スクリーンショット 2022-06-14 195812](https://user-images.githubusercontent.com/97950128/173562840-8c45e6a2-cc3a-44cd-a302-3017c1eb629a.png)

**Comment by notfood** [comment]
It's my bad... I didn't put translations strings to it. I'll note it down to update it.
https://github.com/notfood/RimWorld-Infused/blob/master/Source/CompTargetable_WeaponOrApparel.cs#L134-L154

**Comment by C-ljur** [comment]
Thanks!

**Comment by notfood** [comment]
Should be fixed for 1.4
