### ISSUE TITLE
Infused labels visible on 2nd map

### ISSUE THREAD

**Issue by Killface1980** [notfood/RimWorld-Infused#4]
See here, started a 2nd colony  while ago. Haven't noticed it before, maybe because it wasn't there or I didn't pan to that location before. Positions (x/y/z) seem to be identical.
![image](https://user-images.githubusercontent.com/16738568/29750864-a714860c-8b47-11e7-8628-752554d6abe3.png)
![image](https://user-images.githubusercontent.com/16738568/29750865-b2753d8e-8b47-11e7-82b8-eb3b1d2a23dd.png)

**Comment by notfood** [comment]
InfusionLabelManager is a static class, it's being shared for every MapComponent created. It's causing the issue. Need to roll it all into the MapComponent instead.

**Comment by notfood** [comment]
Can you test? Try the DLL.

https://github.com/notfood/RimWorld-Infused/commit/1a3671812db9ebfdb372fdaff3bda08fceb4763f

**Comment by Killface1980** [comment]
Tested, working as expected. Labels now appear only where they should.
