### ISSUE TITLE
Is market value explosion on pawns intentional?

### ISSUE THREAD

**Issue by macrojames** [notfood/RimWorld-Infused#5]
The +150% market value on infused items lets the wealth skyrocket.
A double infused duster may raise to $700. But on the pawns value explodes if he is wearing more than one double infused item.
Usally in late game the pawns should have an value ranging up to $10k.

Any single double infused item will more than double their value (150% * 150% * $10k = 22,5k)
This gets even worse with more infused items worn. I have a pawn worth $480835.
![infused_mv](https://user-images.githubusercontent.com/482151/50722542-341c7400-10d1-11e9-9a65-3f694fe9a541.png)
I know this is a high quality character but I have the feeling it shouldn't stack the market value that high for pawns. the items are worth about $200 -$600 besides the weapon.
But equipped on the pawn they can be worth $200k. 

In my opinion the market value factor **should be excluded, capped or always calulated on the base value for pawns** in
https://github.com/notfood/RimWorld-Infused/blob/3de0e1b4c998bf3fc2d3fed83e62a6cfea4268ba/Source/StatPart_InfusedModifier.cs#L28

You can close this issue if that is intentional behavior.

**Comment by notfood** [comment]
Not intentional. It's only meant to affect the apparel. I guess I'll add a hardcoded blacklist of Stats that shouldn't go to pawn. Or possibly a ModExtension to ignore them.

**Comment by notfood** [comment]
Can you test this commit? https://github.com/notfood/RimWorld-Infused/commit/7a2d87d63a1d663f03ddbc3b8f0eb34caf16864f

**Comment by macrojames** [comment]
Market value is fixed.

Not sure about the additional changes about armor. I still have armor on a pawn with "invulnerable" infusion.

**Comment by notfood** [comment]
It's for animals, requires another mod.
